# ReconChain package
from __future__ import annotations

# The package is structured so that reconchain.py (single file) has been
# split into submodules within this package.  All public symbols are
# re-exported here for backward compatibility.

from reconchain.config import (
    __version__,
    VALID_PHASES,
    FAST_PHASES,
    PipelineConfig,
    _HOSTNAME_RE,
    _SAFE_HOST,
)
from reconchain.utils import (
    _is_valid_hostname,
    _is_under_domain,
    _target_token,
    _target_lines,
    _write_target_tokens,
    _color, C, LVL,
    disable_color,
    log,
    _auto_detect_proxy,
    _set_proxy_env,
    _auto_detect_cookies,
    _extra_headers_dict,
    _extra_http_args,
    _get_urlopener,
    _get_no_redirect_urlopener,
    _NoRedirectHandler,
    _async_urlopen,
    _async_urlopen_no_redirect,
    _throttle, _throttle_rate, _throttle_sync,
    ensure,
    _existing_artifacts,
    read_lines, iter_lines, count_nonblank,
    merge_unique, merge_unique_str,
    _downsample_file,
    safe_suffix, _safe_name,
    read_jsonl,
    _extract_urls_from_ffuf_json,
    _merge_dnsx_output,
    _dedupe_by_host_path, _dedupe_by_host_params,
    html_escape, md_escape,
    _parse_httpx_tech,
    _mmh3_hash,
    Progress,
    ScanStatus,
)
from reconchain.tools import Tools
from reconchain.process import (
    _run_blocking, _run, run_parallel,
    _needs_proxychains,
    StepResult,
    _wait_proc, _kill_proc, _cleanup_child_procs, _register_proc,
    _maybe_timeout,
    _update_nuclei_templates,
    _atomic_write_json,
    _parse_phase_csv, _domain_arg, _csv_from_phases,
    MAX_PARALLEL_JOBS,
    _USE_PROXYCHAINS,
    _SPAWNED_PIDS, _SPAWNED_PIDS_LOCK,
    _JOB_SEM, _PIPELINE_CFG, _TOOL_RC_REGISTRY,
)
from reconchain.interactsh import Interactsh
from reconchain.reporting import (
    _counts, write_summary, write_html,
    write_full_summary, write_markdown,
)
import re as _re

from reconchain.phases import (
    PIPELINE, _PHASE_WEIGHTS, STAGES, _RECON_LEVELS, PhaseSet,
    _parse_semver, _semver_lt,
    _JS_SECRET_PATTERNS, _SOURCE_MAP_RE,
    _AUTH_BYPASS_HEADERS, _MASS_ASSIGN_FIELDS,
    phase_00_SCOPE,
    phase_01_RECON,
    phase_02_RESOLVE,
    phase_03_PERMUTE,
    phase_04_SCAN,
    phase_04b_TAKEOVER_VALIDATE,
    phase_05_HARVEST,
    phase_05b_APISPEC,
    phase_06_JSINTEL,
    phase_07_PARAMS,
    phase_08_FUZZ,
    phase_09_VULNSCAN,
    phase_10_TLSCMS,
    phase_11_INJECT,
    phase_11b_SQLMAP,
    phase_12_SSTI,
    phase_13_OOB,
    phase_14_ORIGIN,
    phase_15_SECRETS,
    phase_16A_AUTHZ,
    phase_16B_MASSASSIGN,
    phase_17_IDOR,
    phase_17b_SSRFMETA,
    phase_18_CLOUD,
    phase_19_GIT,
    phase_20_GRAPHQL,
    phase_21_WAF,
    phase_22_NOSQLI,
    phase_23_RACE,
    phase_24_JWT,
    phase_25_XXE,
    phase_26_CMDINJECT,
    phase_27_SSPP,
    phase_28_CACHED,
    phase_29_DEPCHECK,
    phase_30_LFI,
    phase_31_OPENREDIR,
    phase_32_CLICKJACK,
    phase_33_CRLF,
    phase_34_RATELIMIT,
    phase_35_CORSADV,
    phase_36_JWTADV,
    phase_37_FILEUPLOAD,
    phase_38_SMUGGLE,
    phase_39_OAUTH,
    phase_40_PWRESET,
    phase_41_WEBSOCKET,
    phase_42_LDAP,
    phase_43_DESERIAL,
    phase_44_CHAIN,
    phase_45_EVIDENCE,
    phase_46_BUCKET,
    phase_47_CDN,
    phase_48_CONTENT,
)
from reconchain.pipeline import run_pipeline
from reconchain.cli import build_parser, main, interactive_setup
from reconchain.dedup import DedupEngine
from reconchain.monitor import MonitorEngine
from reconchain.ratelimit import RateLimiter
from reconchain.useragent import UARotator

__all__ = [
    "__version__", "VALID_PHASES", "FAST_PHASES", "PhaseSet",
    "PIPELINE", "_PHASE_WEIGHTS", "STAGES", "PipelineConfig",
    "_parse_semver", "_semver_lt",
    "_JS_SECRET_PATTERNS", "_SOURCE_MAP_RE",
    "_AUTH_BYPASS_HEADERS", "_MASS_ASSIGN_FIELDS", "_re",
    "_RECON_LEVELS", "_HOSTNAME_RE", "_SAFE_HOST",
    "_is_valid_hostname", "_is_under_domain", "_target_token",
    "_target_lines", "_write_target_tokens",
    "_color", "C", "LVL", "disable_color", "log",
    "_auto_detect_proxy", "_set_proxy_env", "_auto_detect_cookies",
    "_extra_headers_dict", "_extra_http_args", "_get_urlopener",
    "_get_no_redirect_urlopener", "_NoRedirectHandler",
    "_async_urlopen", "_async_urlopen_no_redirect",
    "_throttle", "_throttle_rate", "_throttle_sync",
    "ensure", "_existing_artifacts", "read_lines", "iter_lines",
    "count_nonblank", "merge_unique", "merge_unique_str", "_downsample_file",
    "safe_suffix", "_safe_name", "read_jsonl",
    "_extract_urls_from_ffuf_json", "_merge_dnsx_output",
    "_dedupe_by_host_path", "_dedupe_by_host_params",
    "html_escape", "md_escape", "_parse_httpx_tech",
    "_mmh3_hash", "Progress", "ScanStatus",
    "Tools",
    "_run_blocking", "_run", "run_parallel",
    "_needs_proxychains", "StepResult",
    "_wait_proc", "_kill_proc", "_cleanup_child_procs", "_register_proc",
    "_maybe_timeout", "_update_nuclei_templates",
    "_atomic_write_json", "_parse_phase_csv", "_domain_arg", "_csv_from_phases",
    "MAX_PARALLEL_JOBS", "_USE_PROXYCHAINS",
    "_SPAWNED_PIDS", "_SPAWNED_PIDS_LOCK",
    "_JOB_SEM", "_PIPELINE_CFG", "_TOOL_RC_REGISTRY",
    "Interactsh",
    "_counts", "write_summary", "write_html",
    "write_full_summary", "write_markdown",
    "phase_00_SCOPE", "phase_01_RECON", "phase_02_RESOLVE",
    "phase_03_PERMUTE", "phase_04_SCAN", "phase_04b_TAKEOVER_VALIDATE",
    "phase_05_HARVEST", "phase_05b_APISPEC", "phase_06_JSINTEL",
    "phase_07_PARAMS", "phase_08_FUZZ", "phase_09_VULNSCAN",
    "phase_10_TLSCMS", "phase_11_INJECT", "phase_11b_SQLMAP",
    "phase_12_SSTI", "phase_13_OOB", "phase_14_ORIGIN",
    "phase_15_SECRETS", "phase_16A_AUTHZ", "phase_16B_MASSASSIGN",
    "phase_17_IDOR", "phase_17b_SSRFMETA", "phase_18_CLOUD",
    "phase_19_GIT", "phase_20_GRAPHQL", "phase_21_WAF",
    "phase_22_NOSQLI", "phase_23_RACE", "phase_24_JWT",
    "phase_25_XXE", "phase_26_CMDINJECT", "phase_27_SSPP",
    "phase_28_CACHED", "phase_29_DEPCHECK", "phase_30_LFI",
    "phase_31_OPENREDIR", "phase_32_CLICKJACK", "phase_33_CRLF",
    "phase_34_RATELIMIT", "phase_35_CORSADV", "phase_36_JWTADV",
    "phase_37_FILEUPLOAD", "phase_38_SMUGGLE", "phase_39_OAUTH",
    "phase_40_PWRESET", "phase_41_WEBSOCKET", "phase_42_LDAP",
    "phase_43_DESERIAL",     "phase_44_CHAIN", "phase_45_EVIDENCE",
    "phase_46_BUCKET", "phase_47_CDN", "phase_48_CONTENT",
    "build_parser", "main", "interactive_setup",
    "run_pipeline",
    "DedupEngine", "MonitorEngine", "RateLimiter", "UARotator",
]
