"""Subprocess management, job scheduling, and pipeline helpers."""
from __future__ import annotations
import argparse
import asyncio
import contextlib
import json
import math
import os
import resource
import shutil
import signal
import subprocess
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Set, Tuple

from reconchain.config import VALID_PHASES, _HOSTNAME_RE, PipelineConfig, DISCOVERY_PHASES
from reconchain.utils import ensure, log, _set_proxy_env, _patch_socks, _unpatch_socks

try:
    from tqdm import tqdm
except ImportError:
    class tqdm:
        def __init__(self, *args, **kwargs): pass
        def update(self, n=1): pass
        def set_description(self, desc=None, refresh=True): pass
        def close(self): pass
        @classmethod
        def write(cls, msg="", *args, **kwargs): print(msg, flush=True)


@dataclass
class StepResult:
    name: str
    cmd: List[str]
    rc: int
    duration: float
    log_path: Optional[Path] = None
    note: str = ""


MAX_PARALLEL_JOBS = max(4, os.cpu_count() or 4)
_USE_PROXYCHAINS = False
_SPAWNED_PIDS: List[int] = []
_SPAWNED_PIDS_LOCK = threading.Lock()
_JOB_SEM: Optional[asyncio.Semaphore] = None
_PIPELINE_CFG: PipelineConfig = PipelineConfig()
_PROXY_TIMEOUT_MULTIPLIER: float = 1.5
_PROXY_LOCK: asyncio.Lock = asyncio.Lock()
_TOOL_RC_REGISTRY: Dict[str, int] = {}

# Hard OS-level process counter — limits total concurrent subprocesses
# across all semaphore/gather paths. Defaults to 3 to match typical VM vCPU count.
_OS_PROC_SEM = threading.Semaphore(3)
_OS_PROC_ACTIVE = 0
_OS_PROC_ACTIVE_LOCK = threading.Lock()

# Per-child resource limits (in bytes / counts)
_CHILD_VMEM_LIMIT = 8 * 1024 * 1024 * 1024  # 8 GB virtual address space (Go binaries need large VA)
_CHILD_NPROC_LIMIT = 2048                    # max child processes per tool (xargs/nmap scripts need headroom)
_CHILD_FSIZE_LIMIT = 512 * 1024 * 1024        # 512 MB max output file size


def reset_globals() -> None:
    """Reset module-level globals for clean re-invocation (e.g., in tests)."""
    global _USE_PROXYCHAINS, _JOB_SEM, _PIPELINE_CFG, _PROXY_TIMEOUT_MULTIPLIER
    global _OS_PROC_ACTIVE
    _USE_PROXYCHAINS = False
    _JOB_SEM = None
    _PIPELINE_CFG = PipelineConfig()
    _PROXY_TIMEOUT_MULTIPLIER = 1.5
    _OS_PROC_ACTIVE = 0
    with _SPAWNED_PIDS_LOCK:
        _SPAWNED_PIDS.clear()
    _TOOL_RC_REGISTRY.clear()


def _set_child_limits() -> None:
    """preexec_fn: apply resource limits to every spawned child process.

    Caps virtual memory, max child processes, and max file size to prevent
    a single tool from exhausting the host's resources and crashing the VM.
    """
    try:
        resource.setrlimit(resource.RLIMIT_AS, (_CHILD_VMEM_LIMIT, _CHILD_VMEM_LIMIT))
    except (ValueError, OSError):
        pass
    try:
        resource.setrlimit(resource.RLIMIT_NPROC, (_CHILD_NPROC_LIMIT, _CHILD_NPROC_LIMIT))
    except (ValueError, OSError):
        pass
    try:
        resource.setrlimit(resource.RLIMIT_FSIZE, (_CHILD_FSIZE_LIMIT, _CHILD_FSIZE_LIMIT))
    except (ValueError, OSError):
        pass


def _needs_proxychains(cmd: List[str]) -> bool:
    if not _USE_PROXYCHAINS:
        return False
    if len(cmd) < 2:
        return False
    # Python probe scripts (TLS check, SSRF, blind XSS) use raw sockets
    # that don't respect HTTP_PROXY env vars — they need proxychains.
    if cmd[0] in ("python3", "python") and isinstance(cmd[1], str) and cmd[1].endswith(".py"):
        return True
    # Standalone tools that don't respect proxy env vars natively
    if cmd[0] in ("waymore", "cloud_enum",
                   "wafw00f", "wafw00f.py", "gowitness", "gitdumper",
                   "Gxss", "kxss", "interactsh-client", "arjun"):
        return True
    # Bash runner scripts (generated by the pipeline in out_*/logs/) need proxychains,
    # except DNS tool wrappers — proxychains slows DNS queries unnecessarily.
    if cmd[0] == "bash" and isinstance(cmd[1], str) and cmd[1].endswith((".sh", ".bash")):
        for _t in _DNS_TOOLS:
            if _t in cmd[1]:
                return False
        return True
    return False


def _proxify_cmd(cmd: List[str]) -> List[str]:
    """Prepend proxychains4 when SOCKS proxy is active and tool needs it."""
    if _needs_proxychains(cmd):
        return ["proxychains4"] + cmd
    return cmd


_PROXY_VARS = ["ALL_PROXY", "all_proxy", "HTTPS_PROXY", "https_proxy",
               "HTTP_PROXY", "http_proxy", "PROXY"]

_DNS_TOOLS = {"massdns", "dnsx", "puredns", "dig", "nslookup", "host", "subfinder", "amass"}
_RAW_TOOLS = {"nmap", "naabu"}

def _bypass_proxy(cmd: List[str]) -> bool:
    """Return True if the command should bypass the proxy entirely.
    DNS tools should NEVER go through SOCKS/proxychains — DNS resolution does
    not need anonymity and DNS-over-SOCKS is notoriously slow.
    Port scanners (nmap, naabu) also bypass — they use raw/stealth packets that
    cannot be routed through a TCP-only proxy."""
    if not cmd:
        return False
    if cmd[0] in _DNS_TOOLS | _RAW_TOOLS:
        return True
    # Bash wrappers of DNS tools (e.g., amass.sh) should also bypass proxy
    if cmd[0] == "bash" and len(cmd) > 1:
        for _t in _DNS_TOOLS | _RAW_TOOLS:
            if _t in cmd[1]:
                return True
    return False


def _run_blocking(cmd: List[str], timeout: int, cwd: Optional[Path], log_path: Path) -> Tuple[int, float]:
    global _OS_PROC_ACTIVE
    cmd = _proxify_cmd(cmd)
    t0 = time.monotonic()
    log_path.parent.mkdir(parents=True, exist_ok=True)
    err_path = log_path.with_suffix(log_path.suffix + ".stderr")

    # Save and clear proxy env for DNS tools (Go tools like dnsx respect ALL_PROXY natively)
    _saved_proxy: Dict[str, Optional[str]] = {}
    if _bypass_proxy(cmd):
        for v in _PROXY_VARS:
            _saved_proxy[v] = os.environ.pop(v, None)

    # Block until we're within the hard OS process cap
    _OS_PROC_SEM.acquire()
    with _OS_PROC_ACTIVE_LOCK:
        _OS_PROC_ACTIVE += 1
    try:
        with log_path.open("wb") as logf, err_path.open("wb") as errf:
            proc: Optional[subprocess.Popen[bytes]] = None
            try:
                proc = subprocess.Popen(
                    cmd,
                    cwd=str(cwd) if cwd else None,
                    stdin=subprocess.DEVNULL,
                    stdout=logf,
                    stderr=errf,
                    start_new_session=True,
                    preexec_fn=_set_child_limits,
                )
                _register_proc(proc)
                if not _wait_proc(proc, timeout):
                    _kill_proc(proc)
                    with log_path.open("ab") as f:
                        f.write(f"\n[timeout after {timeout}s]\n".encode("utf-8"))
                    return 124, time.monotonic() - t0
                return proc.returncode, time.monotonic() - t0
            except FileNotFoundError as e:
                with log_path.open("ab") as f:
                    f.write(f"\n[binary not found: {e}]\n".encode("utf-8"))
                return 127, time.monotonic() - t0
            except (PermissionError, OSError) as e:
                with log_path.open("ab") as f:
                    f.write(f"\n[exec error: {e}]\n".encode("utf-8"))
                return 127, time.monotonic() - t0
            finally:
                if proc is not None:
                    with _SPAWNED_PIDS_LOCK, contextlib.suppress(ValueError):
                        _SPAWNED_PIDS.remove(proc.pid)
    finally:
        with _OS_PROC_ACTIVE_LOCK:
            _OS_PROC_ACTIVE = max(0, _OS_PROC_ACTIVE - 1)
        _OS_PROC_SEM.release()
        # Restore proxy env vars after DNS tool completes
        if _saved_proxy:
            for v, val in _saved_proxy.items():
                if val is not None:
                    os.environ[v] = val


async def _run(name: str, cmd: List[str], timeout: int, outdir: Path, note: str = "", quiet: bool = False) -> StepResult:
    if not cmd:
        log("skip", f"{name} (missing tool)")
        return StepResult(name, [], 0, 0.0, outdir / "logs" / f"{name}.log", note=note or "skipped")
    logp = outdir / "logs" / f"{name}.log"
    if not quiet:
        log("info", f"{name}  $ {cmd[0]} {(' '.join(cmd[1:3]))}{' ...' if len(cmd) > 3 else ''}")

    async def _exec() -> StepResult:
        rc, dur = await asyncio.to_thread(_run_blocking, cmd, timeout, outdir, logp)
        lvl = "ok" if rc == 0 else "warn" if rc in (1, 2, 124, 127) or rc < 0 else "err"
        if not quiet:
            log(lvl, f"{name} -> rc={rc} in {dur:.1f}s")
        if rc not in (0, None) and note != "skipped":
            _TOOL_RC_REGISTRY[name] = rc
        return StepResult(name, cmd, rc, dur, logp, note=note)

    sem = _JOB_SEM
    if sem is not None:
        async with sem:
            return await _exec()
    return await _exec()


def _wait_proc(proc: subprocess.Popen, timeout: int) -> bool:
    try:
        proc.wait(timeout=timeout)
        return True
    except subprocess.TimeoutExpired:
        return False


def _kill_proc(proc: subprocess.Popen) -> None:
    try:
        os.killpg(proc.pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        return
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except (ProcessLookupError, PermissionError, OSError):
            pass
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            pass


def _cleanup_child_procs() -> None:
    if not _SPAWNED_PIDS_LOCK.acquire(timeout=5):
        return
    try:
        for pid in list(_SPAWNED_PIDS):
            try:
                os.kill(pid, 0)  # Check if process exists
            except (ProcessLookupError, PermissionError, OSError):
                continue
            with contextlib.suppress(ProcessLookupError, OSError):
                os.killpg(pid, signal.SIGTERM)
            with contextlib.suppress(ProcessLookupError, OSError):
                os.waitpid(pid, os.WNOHANG)
        _SPAWNED_PIDS.clear()
    finally:
        _SPAWNED_PIDS_LOCK.release()


def _register_proc(proc: subprocess.Popen) -> None:
    with _SPAWNED_PIDS_LOCK:
        _SPAWNED_PIDS.append(proc.pid)


def _maybe_timeout(base: int) -> int:
    return int(base * _PROXY_TIMEOUT_MULTIPLIER) if _USE_PROXYCHAINS else base


_PROXY_STATE_STACK: List[Dict[str, Any]] = []
_PROXY_SNAPSHOT: Dict[str, Any] = {"use_proxychains": False, "proxy": "", "timeout_mult": 1.5}
_PROXY_SNAPSHOT_LOCK = threading.Lock()


def get_proxy_state() -> Dict[str, Any]:
    """Thread-safe snapshot of current proxy state for readers."""
    with _PROXY_SNAPSHOT_LOCK:
        return dict(_PROXY_SNAPSHOT)

async def _push_phase_proxy(name: str, proxy: str, vuln_proxy: str) -> None:
    """Save current proxy state and set it for the given phase.
    Vuln phases use `vuln_proxy` (or `proxy` as fallback).
    Discovery phases bypass proxy entirely (DNS/port tools don't work over SOCKS)."""
    global _USE_PROXYCHAINS, _PIPELINE_CFG, _PROXY_TIMEOUT_MULTIPLIER, _PROXY_STATE_STACK
    async with _PROXY_LOCK:
        is_discovery = name in DISCOVERY_PHASES
        phase_proxy = proxy if is_discovery else (vuln_proxy or proxy)

        _PROXY_STATE_STACK.append({
            "_USE_PROXYCHAINS": _USE_PROXYCHAINS,
            "_PIPELINE_CFG_proxy": _PIPELINE_CFG.proxy,
            "_PROXY_TIMEOUT_MULTIPLIER": _PROXY_TIMEOUT_MULTIPLIER,
            "_env": {v: os.environ.get(v) for v in _PROXY_VARS},
        })

        if phase_proxy and not is_discovery:
            _set_proxy_env(phase_proxy)
            _USE_PROXYCHAINS = bool(shutil.which("proxychains4") and phase_proxy.startswith("socks"))
            _PIPELINE_CFG.proxy = phase_proxy
            _PROXY_TIMEOUT_MULTIPLIER = _PIPELINE_CFG.proxy_timeout_multiplier
            if phase_proxy.startswith(("socks4://", "socks5://", "socks5h://", "socks4a://")):
                _patch_socks(phase_proxy)
        else:
            _USE_PROXYCHAINS = False
            _PIPELINE_CFG.proxy = ""
            for v in _PROXY_VARS:
                os.environ.pop(v, None)
            _unpatch_socks()
        with _PROXY_SNAPSHOT_LOCK:
            _PROXY_SNAPSHOT["use_proxychains"] = _USE_PROXYCHAINS
            _PROXY_SNAPSHOT["proxy"] = _PIPELINE_CFG.proxy
            _PROXY_SNAPSHOT["timeout_mult"] = _PROXY_TIMEOUT_MULTIPLIER


async def _pop_phase_proxy() -> None:
    """Restore the proxy state saved by _push_phase_proxy."""
    global _USE_PROXYCHAINS, _PIPELINE_CFG, _PROXY_TIMEOUT_MULTIPLIER, _PROXY_STATE_STACK
    async with _PROXY_LOCK:
        if not _PROXY_STATE_STACK:
            return
        saved = _PROXY_STATE_STACK.pop()
        _USE_PROXYCHAINS = saved["_USE_PROXYCHAINS"]
        _PIPELINE_CFG.proxy = saved["_PIPELINE_CFG_proxy"]
        _PROXY_TIMEOUT_MULTIPLIER = saved["_PROXY_TIMEOUT_MULTIPLIER"]
        for v, val in saved["_env"].items():
            if val is not None:
                os.environ[v] = val
            else:
                os.environ.pop(v, None)
        with _PROXY_SNAPSHOT_LOCK:
            _PROXY_SNAPSHOT["use_proxychains"] = _USE_PROXYCHAINS
            _PROXY_SNAPSHOT["proxy"] = _PIPELINE_CFG.proxy
            _PROXY_SNAPSHOT["timeout_mult"] = _PROXY_TIMEOUT_MULTIPLIER


async def run_parallel(jobs: List[Tuple[str, List[str], int]], outdir: Path, desc: str = "jobs", quiet: bool = False) -> List[StepResult]:
    pbar = tqdm(total=len(jobs), desc=desc, leave=False)

    async def _run_and_update(n: str, c: List[str], t: int) -> StepResult:
        res = await _run(n, c, t, outdir, quiet=quiet)
        pbar.update(1)
        return res

    coros = [_run_and_update(n, c, t) for n, c, t in jobs]
    try:
        return await asyncio.gather(*coros)
    finally:
        pbar.close()


async def _update_nuclei_templates(outdir: Path, proxy: str = "") -> None:
    if not shutil.which("nuclei"):
        return
    cache_stamp = outdir / ".nuclei_update_stamp"
    if cache_stamp.exists():
        try:
            age = time.time() - float(cache_stamp.read_text(encoding="utf-8", errors="ignore").strip())
            if age < 86400:
                return
        except (ValueError, OSError):
            pass
    log("info", "Updating nuclei templates...")
    _proxy = proxy or _PIPELINE_CFG.proxy
    _nu_cmd = ["nuclei", "-update-templates", "-silent"]
    if _proxy:
        _nu_cmd += ["-proxy", _proxy]
    _nu_cmd = _proxify_cmd(_nu_cmd)
    # Gate behind OS process counter so template updates don't consume
    # a slot that could be used by actual recon tools.
    _OS_PROC_SEM.acquire()
    try:
        proc = await asyncio.create_subprocess_exec(
            *_nu_cmd,
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        try:
            rc = await asyncio.wait_for(proc.wait(), timeout=120)
            if rc == 0:
                cache_stamp.write_text(str(time.time()))
            else:
                log("warn", f"nuclei -update-templates returned {rc}")
        except asyncio.TimeoutError:
            proc.kill()
            await proc.wait()
            log("warn", "nuclei -update-templates timed out")
    finally:
        _OS_PROC_SEM.release()


def _atomic_write_json(path: Path, payload: dict) -> None:
    import tempfile
    ensure(path)
    if path.is_symlink():
        real = path.resolve()
        if not real.is_relative_to(path.parent.resolve()):
            path.unlink()
    fd, tmp_path = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(payload, f, indent=2, default=str)
        os.replace(tmp_path, path)
    except Exception:
        with contextlib.suppress(Exception):
            os.unlink(tmp_path)
        raise
    # Verify the write succeeded and the target is a regular file (not a symlink
    # swapped by an attacker between mkstemp and os.replace)
    if path.is_symlink():
        real = path.resolve()
        if not real.is_relative_to(path.parent.resolve()):
            path.unlink()


def _parse_phase_csv(value: str) -> Set[str]:
    """Parse comma-separated phase list, case-insensitively matching VALID_PHASES.
    Accepts e.g. '04b-TAKEOVER-VALIDATE' or '04B-takeover-validate'."""
    normalized_map = {p.upper(): p for p in VALID_PHASES}
    raw = {p.strip() for p in value.split(",") if p.strip()}
    phases = set()
    for p in raw:
        p_upper = p.upper()
        if p_upper in normalized_map:
            phases.add(normalized_map[p_upper])
        elif p in VALID_PHASES:
            phases.add(p)
        else:
            invalid = sorted(raw - set(normalized_map.values()) - set(normalized_map.keys()))
            raise argparse.ArgumentTypeError(
                f"unknown phase(s): {', '.join(invalid)}; valid phases: "
                f"{', '.join(sorted(VALID_PHASES))}"
            )
    return phases


def _domain_arg(value: str) -> str:
    domain = value.rstrip(".").lower()
    if not _HOSTNAME_RE.match(domain) or "." not in domain:
        raise argparse.ArgumentTypeError(
            "domain must be a valid DNS name with at least one dot, for example example.com"
        )
    return domain


def _csv_from_phases(value: object) -> Set[str]:
    if isinstance(value, set):
        return set(value)
    if isinstance(value, str):
        return _parse_phase_csv(value)
    return set()
