#!/usr/bin/env python3
"""Generate docs/phase-classification.md from the live pipeline.

Classifies every phase in vulnforge.PIPELINE by inspecting its source:

  tool      — shells out to an external security tool (subfinder, nuclei, sqlmap, ...)
  browser   — drives a real browser (playwright/selenium) for DOM/dynamic XSS
  probe     — makes active HTTP/WebSocket/socket requests against the target
  local     — no direct target interaction; aggregates, validates, or diffs artifacts

The inline-source heuristic under-detects "probe" because most phases delegate
HTTP work to shared helpers, so OVERRIDES correct the phases whose intent is
not visible in the phase body itself. Classification is a coarse honesty guard,
not a precise contract — read the phase source for details.

Run:  python3 scripts/classify_phases.py   (writes docs/phase-classification.md)
"""

from __future__ import annotations

import inspect
from collections import Counter, OrderedDict
from pathlib import Path
from typing import Dict

from vulnforge.phases import PIPELINE

BROWSER_MARKERS = ("playwright.async_api", "async_playwright", "selenium.webdriver", "webdriver.")
TOOL_MARKERS = ("_run(", "run_parallel(", "_run_blocking(", "create_subprocess", "subprocess.")
PROBE_MARKERS = (
    "_async_urlopen",
    "_async_urlopen_no_redirect",
    "_get_urlopener",
    "_get_no_redirect_urlopener",
    "urllib.",
    "http.client",
    "websocket",
    "asyncio.open_connection",
    "_request(",
    "_probe_",
    "_run_cmd_clear_proxy",
)

# Phases whose true behavior is not visible in the phase body (shared helpers).
OVERRIDES: Dict[str, str] = {
    "09-VULNSCAN": "tool",  # nuclei scan; "chromium" ref was a tool-availability list
    "11a-DOMXSS": "browser",  # drives playwright/chromium from injection.py
    "177-SELENIUMXSS": "browser",  # drives a browser via playwright
    "41-WEBSOCKET": "probe",  # raw WebSocket handshake via socket helper
    "54-WS-FUZZ": "probe",  # WebSocket message fuzzing
    "175a-WS-DEEP": "probe",  # deep WebSocket fuzzing
    "115-BANNER": "probe",  # connects to SSH/FTP/... ports via _grab_banner
    "119-WILDCARDDNS": "probe",  # resolves random subdomains to test wildcard DNS
    "120-DNSREBIND": "probe",  # resolves target across two queries (rebinding)
    "149-LLMSEC": "probe",  # probes LLM endpoints over HTTP
    "150-LLMLEAK": "probe",
    "151-RAGPOISON": "probe",
    "152-LLMADV": "probe",
    "153-BIZLOGIC": "probe",  # sends crafted requests via shared HTTP helper
    "154-PAYMENT": "probe",
    "155-COUPON": "probe",
    "156-MTENANT": "probe",
    "157-2FA": "probe",
    "159-SAMLADV": "probe",  # sends SAML assertions via _find_sso_endpoints
    "167-H2RAPID": "probe",  # raw HTTP/2 reset flooding
    "168-H3QUIC": "probe",  # raw HTTP/3/QUIC probing
    "169-WEBTRANSPORT": "probe",  # WebTransport over HTTP/3
    "13-OOB": "local",  # reads OAST callbacks written by other phases
    "79-SECRETDIFF": "local",  # diffs secret artifacts between scans
    "162-ELECTRONRCE": "local",  # writes probe descriptions; no network interaction
}


def _classify(name: str, func: object) -> str:
    if name in OVERRIDES:
        return OVERRIDES[name]
    src = inspect.getsource(func)
    if any(m in src for m in BROWSER_MARKERS):
        return "browser"
    if any(m in src for m in TOOL_MARKERS):
        return "tool"
    if any(m in src for m in PROBE_MARKERS):
        return "probe"
    return "local"


def main() -> int:
    classified = OrderedDict((name, _classify(name, func)) for name, func, _ in PIPELINE)
    counts = Counter(classified.values())
    legend = (
        "# Phase Classification\n\n"
        "Generated by `python3 scripts/classify_phases.py` — do not edit by hand.\n\n"
        "Every phase in the 213-phase pipeline is classified by what it actually "
        "does against the target. This exists to make the tool's limits honest: "
        "many phases are shallow heuristic probes, only some shell out to real "
        "external tooling, and a few are pure local aggregation.\n\n"
        "| Kind | Meaning |\n"
        "|------|---------|\n"
        "| `tool` | Shells out to an external security tool (subfinder, nuclei, sqlmap, ...) |\n"
        "| `browser` | Drives a real browser (playwright/selenium) for DOM/dynamic XSS |\n"
        "| `probe` | Sends active HTTP/WebSocket/socket requests and heuristic checks |\n"
        "| `local` | No direct target interaction; aggregates, validates, or diffs artifacts |\n\n"
        "Counts: " + ", ".join(f"{k}={v}" for k, v in counts.items()) + "\n\n"
        "| Phase | Kind |\n"
        "|-------|------|\n"
    )
    rows = "".join(f"| {name} | {kind} |\n" for name, kind in classified.items())
    out = Path(__file__).resolve().parents[1] / "docs" / "phase-classification.md"
    out.write_text(legend + rows)
    print(f"wrote {out} ({len(classified)} phases, {counts})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
