"""VulnForge phase package — re-exports all phases for backward compatibility."""

from __future__ import annotations

from typing import Dict, List, Set

# Re-export helpers and constants
from vulnforge.config import VALID_PHASES
from vulnforge.phases.account import (
    phase_191_ATO,
)
from vulnforge.phases.advanced_inject import (
    phase_175_OAUTHDEVICE,
    phase_177_SELENIUMXSS,
    phase_178_APIRACE,
    phase_179_WAFBYPASS,
    phase_180_SWAGGERABUSE,
    phase_181_MFABYPASS,
    phase_182_CAPTCHABYPASS,
    phase_184_SSRFPARTIAL,
    phase_190_BROTLIORACLE,
)
from vulnforge.phases.auth import (
    _AUTH_BYPASS_HEADERS as _AUTH_BYPASS_HEADERS,
)
from vulnforge.phases.auth import (
    _MASS_ASSIGN_FIELDS as _MASS_ASSIGN_FIELDS,
)
from vulnforge.phases.auth import (
    phase_16a_AUTHZ,
    phase_16b_MASSASSIGN,
    phase_17_IDOR,
    phase_17b_SSRFMETA,
    phase_24_JWT,
    phase_36_JWTADV,
    phase_39_OAUTH,
    phase_40_PWRESET,
    phase_61_OAUTH_ADV,
    phase_65_SESSION,
    phase_82_OAUTHDEEP,
)
from vulnforge.phases.auth_bypass import (
    phase_90_CSRF,
    phase_91_SESSIONFIX,
    phase_92_SAML,
    phase_93_PWDSPRAY,
    phase_94_COOKIEAUDIT,
    phase_95_POSTTEST,
    phase_96_METHODOVERRIDE,
    phase_97_FORCEDBROWSE,
    phase_98_CASEBYPASS,
    phase_99_APIPAGE,
    phase_99a_TABNAB,
    phase_99b_APIKEYLEAK,
    phase_99c_REDIRABUSE,
    phase_99d_LOGTRIGGER,
    phase_99e_XSSSTORED,
    phase_99f_HOSTABUSE,
    phase_99g_AUTHBYPASSADV,
)
from vulnforge.phases.bizlogic import (
    phase_153_BIZLOGIC,
    phase_154_PAYMENT,
    phase_155_COUPON,
    phase_156_MTENANT,
    phase_157_2FA,
)
from vulnforge.phases.client_side import (
    phase_28_CACHED,
    phase_30_LFI,
    phase_31_OPENREDIR,
    phase_32_CLICKJACK,
    phase_33_CRLF,
    phase_34_RATELIMIT,
    phase_35_CORSADV,
    phase_37_FILEUPLOAD,
    phase_73_CSPBYPASS,
    phase_80_STOREXSS,
)
from vulnforge.phases.client_side_v2 import (
    phase_170_CLIENTPP,
    phase_171_CSSINJECT,
    phase_172_DANGLING,
)
from vulnforge.phases.cloud import (
    phase_127_CICD,
    phase_128_DOCKER,
    phase_129_K8S,
    phase_130_TERRAFORM,
    phase_133_APIVERSION,
    phase_134_LBDETECT,
    phase_135_VHOST,
    phase_136_RATELIMITBYPASS,
)
from vulnforge.phases.cms import (
    phase_121_IISASPNET,
    phase_122_TOMCAT,
    phase_123_NODEJS,
    phase_124_LARAVEL,
    phase_125_DJANGO,
    phase_126_SYMFONY,
    phase_131_ENVDEEP,
    phase_132_GQLABUSE,
)
from vulnforge.phases.cms_deep import (
    phase_185_MAGENTO,
    phase_186_SHAREPOINT,
    phase_187_CONFLUENCE,
    phase_188_CICD,
    phase_189_TOMCAT,
)
from vulnforge.phases.cookie_security import (
    phase_194_COOKIETOSS,
    phase_195_MIMESNIFF,
)
from vulnforge.phases.electron import (
    phase_161_ELECTRON,
    phase_162_ELECTRONRCE,
    phase_163_ELECTRONPROTO,
    phase_164_ELECTRONUPD,
)
from vulnforge.phases.email_misc import (
    phase_59_EMAIL_SEC,
    phase_60_SMTP_ENUM,
    phase_62_LOG_INJECT,
    phase_63_DOC_ATTACK,
    phase_64_IDEMPOTENCY,
    phase_67_PATHNORM,
    phase_71_EMHARVEST,
    phase_72_ACCOUNTENUM,
    phase_74_GHTOOLS,
    phase_75_MOBILEAPI,
    phase_76_WORKFLOW,
    phase_77_CACHEKEY,
    phase_78_FILEUPLOADADV,
    phase_81_IDORFUZZ,
)
from vulnforge.phases.encoding import (
    phase_100_SSI,
    phase_101_JSONINJECT,
    phase_102_NULLBYTE,
    phase_103_DOUBLEENCOD,
    phase_104_UNICODE,
    phase_105_POSTMSGXSS,
    phase_106_JSONP,
)
from vulnforge.phases.extended import (
    phase_137_EMAILFINDER,
    phase_138_METAGOOFIL,
    phase_139_PORCHPIRATE,
    phase_140_DORKHUNTER,
    phase_141_CRTSH,
    phase_142_GITHUBSUB,
    phase_143_TLSX,
    phase_144_ANALYTICSRELS,
    phase_145_FAVIRECON,
    phase_146_JSLUICE,
    phase_147_SHORTSCAN,
    phase_148_GRPCURL,
)
from vulnforge.phases.fuzzing import (
    phase_08_FUZZ,
    phase_21_WAF,
    phase_21b_WAFBYPASS,
    phase_54_WS_FUZZ,
)
from vulnforge.phases.graphql_chain import (
    phase_20_GRAPHQL,
    phase_44_CHAIN,
    phase_45_EVIDENCE,
)
from vulnforge.phases.helpers import (
    _SCOPE_FILE as _SCOPE_FILE,
)
from vulnforge.phases.helpers import (
    _SCOPE_PATTERNS as _SCOPE_PATTERNS,
)
from vulnforge.phases.helpers import (
    PhaseSet as PhaseSet,
)
from vulnforge.phases.helpers import (
    _dedupe_by_normalized_url as _dedupe_by_normalized_url,
)
from vulnforge.phases.helpers import (
    _normalize_url as _normalize_url,
)
from vulnforge.phases.helpers import (
    _rate_limit_args as _rate_limit_args,
)
from vulnforge.phases.injection import (
    phase_11_INJECT,
    phase_11a_DOMXSS,
    phase_11b_SQLMAP,
    phase_12_SSTI,
)
from vulnforge.phases.injection_misc import (
    _parse_semver as _parse_semver,
)
from vulnforge.phases.injection_misc import (
    _semver_lt as _semver_lt,
)
from vulnforge.phases.injection_misc import (
    phase_22_NOSQLI,
    phase_25_XXE,
    phase_26_CMDINJECT,
    phase_27_SSPP,
    phase_29_DEPCHECK,
    phase_42_LDAP,
    phase_43_DESERIAL,
    phase_66_SSRF_FULL,
    phase_69_DNSZT,
    phase_70_PORTFULL,
)
from vulnforge.phases.llm_ai import (
    phase_149_LLMSEC,
    phase_150_LLMLEAK,
    phase_151_RAGPOISON,
    phase_152_LLMADV,
)
from vulnforge.phases.modern_proto import (
    phase_167_H2RAPID,
    phase_168_H3QUIC,
    phase_169_WEBTRANSPORT,
)
from vulnforge.phases.modern_web import (
    phase_173_SERVICEWORKER,
    phase_174_WASMSEC,
    phase_176_JWT2SELF,
)
from vulnforge.phases.network import (
    phase_112_RFI,
    phase_113_WEBDAV,
    phase_114_SNMP,
    phase_115_BANNER,
    phase_116_PHPINFO,
    phase_117_SRVSTATUS,
    phase_118_ERRORLEAK,
    phase_119_WILDCARDDNS,
    phase_120_DNSREBIND,
)
from vulnforge.phases.origin_cloud import (
    phase_14_ORIGIN,
    phase_18_CLOUD,
    phase_46_BUCKET,
    phase_50_BUCKET_PERMS,
)
from vulnforge.phases.protocol import (
    phase_183_CACHEDIG,
)
from vulnforge.phases.pwa_security import (
    phase_196_PUSHAPI,
)

# Re-export all phase functions from submodules
from vulnforge.phases.recon import (
    _JS_SECRET_PATTERNS as _JS_SECRET_PATTERNS,
)
from vulnforge.phases.recon import (
    _SOURCE_MAP_RE as _SOURCE_MAP_RE,
)
from vulnforge.phases.recon import (
    phase_00_SCOPE,
    phase_01_RECON,
    phase_02_RESOLVE,
    phase_03_PERMUTE,
    phase_04_SCAN,
    phase_04b_TAKEOVER_VALIDATE,
    phase_05_HARVEST,
    phase_05b_APISPEC,
    phase_06_JSINTEL,
    phase_07_PARAMS,
    phase_84_WHOIS,
    phase_85_ASN,
    phase_86_DORK,
    phase_87_SHODAN,
    phase_88_EMPLOYEE,
    phase_89_PASSIVEDNS,
)
from vulnforge.phases.redos import (
    phase_192_REDOS,
)
from vulnforge.phases.secrets_git import (
    phase_15_SECRETS,
    phase_19_GIT,
    phase_79_SECRETDIFF,
)
from vulnforge.phases.smuggling import (
    phase_23_RACE,
    phase_38_SMUGGLE,
    phase_38b_H2SMUGGLE,
    phase_41_WEBSOCKET,
    phase_83_RACEBURST,
    phase_175a_WS_DEEP,
)
from vulnforge.phases.sso import (
    phase_158_SSO,
    phase_159_SAMLADV,
    phase_160_SSOCONF,
)
from vulnforge.phases.supplychain import (
    phase_165_DEPCONF,
    phase_166_TYPOSQUAT,
)
from vulnforge.phases.third_party import (
    phase_107_SRI,
    phase_108_MIXEDCONTENT,
    phase_109_HSTSPRELOAD,
    phase_110_THIRDPARTYJS,
    phase_111_BROWSERSTORAGE,
)
from vulnforge.phases.vuln_scan import (
    phase_09_VULNSCAN,
    phase_10_TLSCMS,
    phase_13_OOB,
    phase_68_DEPCVE,
)
from vulnforge.phases.web_infra import (
    phase_47_CDN,
    phase_48_CONTENT,
    phase_49_FRAMEWORKS,
    phase_51_HPP,
    phase_52_SERVERLESS,
    phase_53_CSP,
    phase_55_CSV_INJECT,
    phase_56_EXPOSED_DB,
    phase_57_DEFAULT_CREDS,
    phase_58_HOST_INJECT,
)
from vulnforge.phases.webrtc import (
    phase_193_WEBRTC,
)

# --- Pipeline data structures (copied verbatim from original phases.py) ---

PIPELINE = [
    ("00-SCOPE", phase_00_SCOPE, ("domain", "outdir", "t", "only", "skip", "force")),
    ("01-RECON", phase_01_RECON, ("domain", "outdir", "t", "only", "skip", "resume", "force")),
    (
        "02-RESOLVE",
        phase_02_RESOLVE,
        ("domain", "outdir", "t", "only", "skip", "prev", "resume", "force"),
    ),
    ("03-PERMUTE", phase_03_PERMUTE, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("04-SCAN", phase_04_SCAN, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "04b-TAKEOVER-VALIDATE",
        phase_04b_TAKEOVER_VALIDATE,
        ("outdir", "t", "only", "skip", "force"),
    ),
    ("05-HARVEST", phase_05_HARVEST, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("05b-APISPEC", phase_05b_APISPEC, ("outdir", "t", "only", "skip", "prev", "force")),
    ("06-JSINTEL", phase_06_JSINTEL, ("outdir", "t", "only", "skip", "force")),
    ("07-PARAMS", phase_07_PARAMS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("08-FUZZ", phase_08_FUZZ, ("outdir", "t", "only", "skip", "force")),
    ("09-VULNSCAN", phase_09_VULNSCAN, ("outdir", "t", "only", "skip", "force")),
    ("10-TLSCMS", phase_10_TLSCMS, ("outdir", "t", "only", "skip", "force")),
    ("11-INJECT", phase_11_INJECT, ("outdir", "t", "only", "skip", "oast_domain", "force")),
    ("11a-DOMXSS", phase_11a_DOMXSS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("11b-SQLMAP", phase_11b_SQLMAP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("12-SSTI", phase_12_SSTI, ("outdir", "t", "only", "skip", "prev", "force")),
    ("13-OOB", phase_13_OOB, ("outdir", "t", "only", "skip", "oast", "force")),
    ("14-ORIGIN", phase_14_ORIGIN, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("15-SECRETS", phase_15_SECRETS, ("outdir", "t", "only", "skip", "force")),
    ("16a-AUTHZ", phase_16a_AUTHZ, ("outdir", "t", "only", "skip", "force")),
    ("16b-MASSASSIGN", phase_16b_MASSASSIGN, ("outdir", "t", "only", "skip", "force")),
    ("17-IDOR", phase_17_IDOR, ("outdir", "t", "only", "skip", "prev", "force")),
    ("17b-SSRFMETA", phase_17b_SSRFMETA, ("outdir", "t", "only", "skip", "prev", "force")),
    ("18-CLOUD", phase_18_CLOUD, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("19-GIT", phase_19_GIT, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("20-GRAPHQL", phase_20_GRAPHQL, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("21-WAF", phase_21_WAF, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("21b-WAFBYPASS", phase_21b_WAFBYPASS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("22-NOSQLI", phase_22_NOSQLI, ("outdir", "t", "only", "skip", "prev", "force")),
    ("23-RACE", phase_23_RACE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("24-JWT", phase_24_JWT, ("outdir", "t", "only", "skip", "force")),
    ("25-XXE", phase_25_XXE, ("outdir", "t", "only", "skip", "prev", "oast_domain", "force")),
    ("26-CMDINJECT", phase_26_CMDINJECT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("27-SSPP", phase_27_SSPP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("28-CACHED", phase_28_CACHED, ("outdir", "t", "only", "skip", "prev", "force")),
    ("29-DEPCHECK", phase_29_DEPCHECK, ("outdir", "t", "only", "skip", "force")),
    ("30-LFI", phase_30_LFI, ("outdir", "t", "only", "skip", "prev", "force")),
    ("31-OPENREDIR", phase_31_OPENREDIR, ("outdir", "t", "only", "skip", "prev", "force")),
    ("32-CLICKJACK", phase_32_CLICKJACK, ("outdir", "t", "only", "skip", "prev", "force")),
    ("33-CRLF", phase_33_CRLF, ("outdir", "t", "only", "skip", "prev", "force")),
    ("34-RATELIMIT", phase_34_RATELIMIT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("35-CORSADV", phase_35_CORSADV, ("outdir", "t", "only", "skip", "prev", "force")),
    ("36-JWTADV", phase_36_JWTADV, ("outdir", "t", "only", "skip", "prev", "force")),
    ("37-FILEUPLOAD", phase_37_FILEUPLOAD, ("outdir", "t", "only", "skip", "prev", "force")),
    ("38-SMUGGLE", phase_38_SMUGGLE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("38b-H2SMUGGLE", phase_38b_H2SMUGGLE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("39-OAUTH", phase_39_OAUTH, ("outdir", "t", "only", "skip", "prev", "force")),
    ("40-PWRESET", phase_40_PWRESET, ("outdir", "t", "only", "skip", "prev", "force")),
    ("41-WEBSOCKET", phase_41_WEBSOCKET, ("outdir", "t", "only", "skip", "prev", "force")),
    ("42-LDAP", phase_42_LDAP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("43-DESERIAL", phase_43_DESERIAL, ("outdir", "t", "only", "skip", "prev", "force")),
    ("44-CHAIN", phase_44_CHAIN, ("outdir", "t", "only", "skip", "prev", "force")),
    ("45-EVIDENCE", phase_45_EVIDENCE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("46-BUCKET", phase_46_BUCKET, ("outdir", "t", "only", "skip", "prev", "force")),
    ("47-CDN", phase_47_CDN, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    ("48-CONTENT", phase_48_CONTENT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("49-FRAMEWORKS", phase_49_FRAMEWORKS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("50-BUCKET-PERMS", phase_50_BUCKET_PERMS, ("outdir", "t", "only", "skip", "force")),
    ("51-HPP", phase_51_HPP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("52-SERVERLESS", phase_52_SERVERLESS, ("outdir", "t", "only", "skip", "force")),
    ("53-CSP", phase_53_CSP, ("outdir", "t", "only", "skip", "force")),
    ("54-WS-FUZZ", phase_54_WS_FUZZ, ("outdir", "t", "only", "skip", "prev", "force")),
    ("55-CSV-INJECT", phase_55_CSV_INJECT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("56-EXPOSED-DB", phase_56_EXPOSED_DB, ("outdir", "t", "only", "skip", "prev", "force")),
    ("57-DEFAULT-CREDS", phase_57_DEFAULT_CREDS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("58-HOST-INJECT", phase_58_HOST_INJECT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("59-EMAIL-SEC", phase_59_EMAIL_SEC, ("domain", "outdir", "t", "only", "skip", "force")),
    ("60-SMTP-ENUM", phase_60_SMTP_ENUM, ("domain", "outdir", "t", "only", "skip", "force")),
    (
        "61-OAUTH-ADV",
        phase_61_OAUTH_ADV,
        ("domain", "outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("62-LOG-INJECT", phase_62_LOG_INJECT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("63-DOC-ATTACK", phase_63_DOC_ATTACK, ("outdir", "t", "only", "skip", "prev", "force")),
    ("64-IDEMPOTENCY", phase_64_IDEMPOTENCY, ("outdir", "t", "only", "skip", "prev", "force")),
    ("65-SESSION", phase_65_SESSION, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "66-SSRF-FULL",
        phase_66_SSRF_FULL,
        ("outdir", "t", "only", "skip", "prev", "oast_domain", "force"),
    ),
    ("67-PATHNORM", phase_67_PATHNORM, ("outdir", "t", "only", "skip", "prev", "force")),
    ("68-DEPCVE", phase_68_DEPCVE, ("outdir", "t", "only", "skip", "force")),
    ("69-DNSZT", phase_69_DNSZT, ("domain", "outdir", "t", "only", "skip", "force")),
    ("70-PORTFULL", phase_70_PORTFULL, ("outdir", "t", "only", "skip", "prev", "force")),
    ("71-EMHARVEST", phase_71_EMHARVEST, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "72-ACCOUNTENUM",
        phase_72_ACCOUNTENUM,
        ("domain", "outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("73-CSPBYPASS", phase_73_CSPBYPASS, ("outdir", "t", "only", "skip", "force")),
    ("74-GHTOOLS", phase_74_GHTOOLS, ("domain", "outdir", "t", "only", "skip", "force")),
    ("75-MOBILEAPI", phase_75_MOBILEAPI, ("domain", "outdir", "t", "only", "skip", "force")),
    ("76-WORKFLOW", phase_76_WORKFLOW, ("outdir", "t", "only", "skip", "prev", "force")),
    ("77-CACHEKEY", phase_77_CACHEKEY, ("outdir", "t", "only", "skip", "prev", "force")),
    ("78-FILEUPLOADADV", phase_78_FILEUPLOADADV, ("outdir", "t", "only", "skip", "prev", "force")),
    ("79-SECRETDIFF", phase_79_SECRETDIFF, ("outdir", "t", "only", "skip", "force")),
    ("80-STOREXSS", phase_80_STOREXSS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("81-IDORFUZZ", phase_81_IDORFUZZ, ("outdir", "t", "only", "skip", "prev", "force")),
    ("82-OAUTHDEEP", phase_82_OAUTHDEEP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("83-RACEBURST", phase_83_RACEBURST, ("outdir", "t", "only", "skip", "prev", "force")),
    ("84-WHOIS", phase_84_WHOIS, ("domain", "outdir", "t", "only", "skip", "force")),
    ("85-ASN", phase_85_ASN, ("domain", "outdir", "t", "only", "skip", "force")),
    ("86-DORK", phase_86_DORK, ("domain", "outdir", "t", "only", "skip", "force")),
    ("87-SHODAN", phase_87_SHODAN, ("domain", "outdir", "t", "only", "skip", "force")),
    ("88-EMPLOYEE", phase_88_EMPLOYEE, ("domain", "outdir", "t", "only", "skip", "force")),
    ("89-PASSIVEDNS", phase_89_PASSIVEDNS, ("domain", "outdir", "t", "only", "skip", "force")),
    ("90-CSRF", phase_90_CSRF, ("outdir", "t", "only", "skip", "prev", "force")),
    ("91-SESSIONFIX", phase_91_SESSIONFIX, ("outdir", "t", "only", "skip", "prev", "force")),
    ("92-SAML", phase_92_SAML, ("outdir", "t", "only", "skip", "prev", "force")),
    ("93-PWDSPRAY", phase_93_PWDSPRAY, ("outdir", "t", "only", "skip", "prev", "force")),
    ("94-COOKIEAUDIT", phase_94_COOKIEAUDIT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("95-POSTTEST", phase_95_POSTTEST, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "96-METHODOVERRIDE",
        phase_96_METHODOVERRIDE,
        ("outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("97-FORCEDBROWSE", phase_97_FORCEDBROWSE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("98-CASEBYPASS", phase_98_CASEBYPASS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("99-APIPAGE", phase_99_APIPAGE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("99a-TABNAB", phase_99a_TABNAB, ("outdir", "t", "only", "skip", "prev", "force")),
    ("99b-APIKEYLEAK", phase_99b_APIKEYLEAK, ("outdir", "t", "only", "skip", "prev", "force")),
    ("99c-REDIRABUSE", phase_99c_REDIRABUSE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("99d-LOGTRIGGER", phase_99d_LOGTRIGGER, ("outdir", "t", "only", "skip", "prev", "force")),
    ("99e-XSSSTORED", phase_99e_XSSSTORED, ("outdir", "t", "only", "skip", "prev", "force")),
    ("99f-HOSTABUSE", phase_99f_HOSTABUSE, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "99g-AUTHBYPASSADV",
        phase_99g_AUTHBYPASSADV,
        ("outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("100-SSI", phase_100_SSI, ("outdir", "t", "only", "skip", "prev", "force")),
    ("101-JSONINJECT", phase_101_JSONINJECT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("102-NULLBYTE", phase_102_NULLBYTE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("103-DOUBLEENCOD", phase_103_DOUBLEENCOD, ("outdir", "t", "only", "skip", "prev", "force")),
    ("104-UNICODE", phase_104_UNICODE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("105-POSTMSGXSS", phase_105_POSTMSGXSS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("106-JSONP", phase_106_JSONP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("107-SRI", phase_107_SRI, ("outdir", "t", "only", "skip", "prev", "force")),
    ("108-MIXEDCONTENT", phase_108_MIXEDCONTENT, ("outdir", "t", "only", "skip", "force")),
    ("109-HSTSPRELOAD", phase_109_HSTSPRELOAD, ("outdir", "t", "only", "skip", "force")),
    ("110-THIRDPARTYJS", phase_110_THIRDPARTYJS, ("outdir", "t", "only", "skip", "force")),
    ("111-BROWSERSTORAGE", phase_111_BROWSERSTORAGE, ("outdir", "t", "only", "skip", "force")),
    ("112-RFI", phase_112_RFI, ("outdir", "t", "only", "skip", "prev", "force")),
    ("113-WEBDAV", phase_113_WEBDAV, ("outdir", "t", "only", "skip", "force")),
    ("114-SNMP", phase_114_SNMP, ("outdir", "t", "only", "skip", "force")),
    ("115-BANNER", phase_115_BANNER, ("outdir", "t", "only", "skip", "prev", "force")),
    ("116-PHPINFO", phase_116_PHPINFO, ("outdir", "t", "only", "skip", "prev", "force")),
    ("117-SRVSTATUS", phase_117_SRVSTATUS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("118-ERRORLEAK", phase_118_ERRORLEAK, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "119-WILDCARDDNS",
        phase_119_WILDCARDDNS,
        ("domain", "outdir", "t", "only", "skip", "prev", "force"),
    ),
    (
        "120-DNSREBIND",
        phase_120_DNSREBIND,
        ("domain", "outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("121-IISASPNET", phase_121_IISASPNET, ("outdir", "t", "only", "skip", "prev", "force")),
    ("122-TOMCAT", phase_122_TOMCAT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("123-NODEJS", phase_123_NODEJS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("124-LARAVEL", phase_124_LARAVEL, ("outdir", "t", "only", "skip", "prev", "force")),
    ("125-DJANGO", phase_125_DJANGO, ("outdir", "t", "only", "skip", "prev", "force")),
    ("126-SYMFONY", phase_126_SYMFONY, ("outdir", "t", "only", "skip", "prev", "force")),
    ("127-CICD", phase_127_CICD, ("outdir", "t", "only", "skip", "prev", "force")),
    ("128-DOCKER", phase_128_DOCKER, ("outdir", "t", "only", "skip", "prev", "force")),
    ("129-K8S", phase_129_K8S, ("outdir", "t", "only", "skip", "prev", "force")),
    ("130-TERRAFORM", phase_130_TERRAFORM, ("outdir", "t", "only", "skip", "prev", "force")),
    ("131-ENVDEEP", phase_131_ENVDEEP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("132-GQLABUSE", phase_132_GQLABUSE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("133-APIVERSION", phase_133_APIVERSION, ("outdir", "t", "only", "skip", "prev", "force")),
    ("134-LBDETECT", phase_134_LBDETECT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("135-VHOST", phase_135_VHOST, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "136-RATELIMITBYPASS",
        phase_136_RATELIMITBYPASS,
        ("outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("137-EMAILFINDER", phase_137_EMAILFINDER, ("domain", "outdir", "t", "only", "skip", "force")),
    ("138-METAGOOFIL", phase_138_METAGOOFIL, ("domain", "outdir", "t", "only", "skip", "force")),
    ("139-PORCHPIRATE", phase_139_PORCHPIRATE, ("domain", "outdir", "t", "only", "skip", "force")),
    ("140-DORKHUNTER", phase_140_DORKHUNTER, ("domain", "outdir", "t", "only", "skip", "force")),
    ("141-CRTSH", phase_141_CRTSH, ("domain", "outdir", "t", "only", "skip", "prev", "force")),
    (
        "142-GITHUBSUB",
        phase_142_GITHUBSUB,
        ("domain", "outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("143-TLSX", phase_143_TLSX, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "144-ANALYTICSRELS",
        phase_144_ANALYTICSRELS,
        ("domain", "outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("145-FAVIRECON", phase_145_FAVIRECON, ("outdir", "t", "only", "skip", "prev", "force")),
    ("146-JSLUICE", phase_146_JSLUICE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("147-SHORTSCAN", phase_147_SHORTSCAN, ("outdir", "t", "only", "skip", "prev", "force")),
    ("148-GRPCURL", phase_148_GRPCURL, ("outdir", "t", "only", "skip", "prev", "force")),
    ("149-LLMSEC", phase_149_LLMSEC, ("outdir", "t", "only", "skip", "prev", "force")),
    ("150-LLMLEAK", phase_150_LLMLEAK, ("outdir", "t", "only", "skip", "prev", "force")),
    ("151-RAGPOISON", phase_151_RAGPOISON, ("outdir", "t", "only", "skip", "prev", "force")),
    ("152-LLMADV", phase_152_LLMADV, ("outdir", "t", "only", "skip", "prev", "force")),
    ("153-BIZLOGIC", phase_153_BIZLOGIC, ("outdir", "t", "only", "skip", "prev", "force")),
    ("154-PAYMENT", phase_154_PAYMENT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("155-COUPON", phase_155_COUPON, ("outdir", "t", "only", "skip", "prev", "force")),
    ("156-MTENANT", phase_156_MTENANT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("157-2FA", phase_157_2FA, ("outdir", "t", "only", "skip", "prev", "force")),
    ("158-SSO", phase_158_SSO, ("outdir", "t", "only", "skip", "prev", "force")),
    ("159-SAMLADV", phase_159_SAMLADV, ("outdir", "t", "only", "skip", "prev", "force")),
    ("160-SSOCONF", phase_160_SSOCONF, ("outdir", "t", "only", "skip", "prev", "force")),
    ("161-ELECTRON", phase_161_ELECTRON, ("outdir", "t", "only", "skip", "prev", "force")),
    ("162-ELECTRONRCE", phase_162_ELECTRONRCE, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "163-ELECTRONPROTO",
        phase_163_ELECTRONPROTO,
        ("outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("164-ELECTRONUPD", phase_164_ELECTRONUPD, ("outdir", "t", "only", "skip", "prev", "force")),
    ("165-DEPCONF", phase_165_DEPCONF, ("outdir", "t", "only", "skip", "prev", "force")),
    ("166-TYPOSQUAT", phase_166_TYPOSQUAT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("167-H2RAPID", phase_167_H2RAPID, ("outdir", "t", "only", "skip", "prev", "force")),
    ("168-H3QUIC", phase_168_H3QUIC, ("outdir", "t", "only", "skip", "prev", "force")),
    ("169-WEBTRANSPORT", phase_169_WEBTRANSPORT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("170-CLIENTPP", phase_170_CLIENTPP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("171-CSSINJECT", phase_171_CSSINJECT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("172-DANGLING", phase_172_DANGLING, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "173-SERVICEWORKER",
        phase_173_SERVICEWORKER,
        ("outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("174-WASMSEC", phase_174_WASMSEC, ("outdir", "t", "only", "skip", "prev", "force")),
    ("175-OAUTHDEVICE", phase_175_OAUTHDEVICE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("175a-WS-DEEP", phase_175a_WS_DEEP, ("outdir", "t", "only", "skip", "prev", "force")),
    ("176-JWT2SELF", phase_176_JWT2SELF, ("outdir", "t", "only", "skip", "prev", "force")),
    ("177-SELENIUMXSS", phase_177_SELENIUMXSS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("178-APIRACE", phase_178_APIRACE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("179-WAFBYPASS", phase_179_WAFBYPASS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("180-SWAGGERABUSE", phase_180_SWAGGERABUSE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("181-MFABYPASS", phase_181_MFABYPASS, ("outdir", "t", "only", "skip", "prev", "force")),
    (
        "182-CAPTCHABYPASS",
        phase_182_CAPTCHABYPASS,
        ("outdir", "t", "only", "skip", "prev", "force"),
    ),
    ("183-CACHEDIG", phase_183_CACHEDIG, ("outdir", "t", "only", "skip", "prev", "force")),
    ("184-SSRFPARTIAL", phase_184_SSRFPARTIAL, ("outdir", "t", "only", "skip", "prev", "force")),
    ("185-MAGENTO", phase_185_MAGENTO, ("outdir", "t", "only", "skip", "prev", "force")),
    ("186-SHAREPOINT", phase_186_SHAREPOINT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("187-CONFLUENCE", phase_187_CONFLUENCE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("188-CICD", phase_188_CICD, ("outdir", "t", "only", "skip", "prev", "force")),
    ("189-TOMCAT", phase_189_TOMCAT, ("outdir", "t", "only", "skip", "prev", "force")),
    ("190-BROTLIORACLE", phase_190_BROTLIORACLE, ("outdir", "t", "only", "skip", "prev", "force")),
    ("191-ATO", phase_191_ATO, ("outdir", "t", "only", "skip", "prev", "force")),
    ("192-REDOS", phase_192_REDOS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("193-WEBRTC", phase_193_WEBRTC, ("outdir", "t", "only", "skip", "prev", "force")),
    ("194-COOKIETOSS", phase_194_COOKIETOSS, ("outdir", "t", "only", "skip", "prev", "force")),
    ("195-MIMESNIFF", phase_195_MIMESNIFF, ("outdir", "t", "only", "skip", "prev", "force")),
    ("196-PUSHAPI", phase_196_PUSHAPI, ("outdir", "t", "only", "skip", "prev", "force")),
]


_PHASE_WEIGHTS: Dict[str, int] = {
    "00-SCOPE": 1,
    "01-RECON": 10,
    "02-RESOLVE": 5,
    "03-PERMUTE": 8,
    "04-SCAN": 10,
    "04b-TAKEOVER-VALIDATE": 3,
    "05-HARVEST": 8,
    "05b-APISPEC": 2,
    "06-JSINTEL": 5,
    "07-PARAMS": 5,
    "08-FUZZ": 10,
    "09-VULNSCAN": 10,
    "10-TLSCMS": 8,
    "11-INJECT": 8,
    "11a-DOMXSS": 6,
    "11b-SQLMAP": 10,
    "12-SSTI": 3,
    "13-OOB": 2,
    "14-ORIGIN": 3,
    "15-SECRETS": 5,
    "16a-AUTHZ": 2,
    "16b-MASSASSIGN": 2,
    "17-IDOR": 3,
    "17b-SSRFMETA": 2,
    "18-CLOUD": 3,
    "19-GIT": 5,
    "20-GRAPHQL": 2,
    "21-WAF": 3,
    "21b-WAFBYPASS": 4,
    "22-NOSQLI": 3,
    "23-RACE": 3,
    "24-JWT": 3,
    "25-XXE": 3,
    "26-CMDINJECT": 5,
    "27-SSPP": 2,
    "28-CACHED": 3,
    "29-DEPCHECK": 5,
    "30-LFI": 3,
    "31-OPENREDIR": 2,
    "32-CLICKJACK": 3,
    "33-CRLF": 3,
    "34-RATELIMIT": 2,
    "35-CORSADV": 3,
    "36-JWTADV": 3,
    "37-FILEUPLOAD": 3,
    "38-SMUGGLE": 5,
    "38b-H2SMUGGLE": 4,
    "39-OAUTH": 3,
    "40-PWRESET": 3,
    "41-WEBSOCKET": 3,
    "42-LDAP": 2,
    "43-DESERIAL": 3,
    "44-CHAIN": 1,
    "45-EVIDENCE": 3,
    "46-BUCKET": 3,
    "47-CDN": 2,
    "48-CONTENT": 5,
    "49-FRAMEWORKS": 4,
    "50-BUCKET-PERMS": 3,
    "51-HPP": 3,
    "52-SERVERLESS": 4,
    "53-CSP": 2,
    "54-WS-FUZZ": 3,
    "55-CSV-INJECT": 3,
    "56-EXPOSED-DB": 4,
    "57-DEFAULT-CREDS": 4,
    "58-HOST-INJECT": 3,
    "59-EMAIL-SEC": 2,
    "60-SMTP-ENUM": 3,
    "61-OAUTH-ADV": 3,
    "62-LOG-INJECT": 3,
    "63-DOC-ATTACK": 4,
    "64-IDEMPOTENCY": 3,
    "65-SESSION": 2,
    "66-SSRF-FULL": 3,
    "67-PATHNORM": 2,
    "68-DEPCVE": 4,
    "69-DNSZT": 1,
    "70-PORTFULL": 8,
    "71-EMHARVEST": 3,
    "72-ACCOUNTENUM": 2,
    "73-CSPBYPASS": 2,
    "74-GHTOOLS": 3,
    "75-MOBILEAPI": 2,
    "76-WORKFLOW": 2,
    "77-CACHEKEY": 2,
    "78-FILEUPLOADADV": 2,
    "79-SECRETDIFF": 1,
    "80-STOREXSS": 4,
    "81-IDORFUZZ": 3,
    "82-OAUTHDEEP": 2,
    "83-RACEBURST": 3,
    "84-WHOIS": 2,
    "85-ASN": 3,
    "86-DORK": 4,
    "87-SHODAN": 3,
    "88-EMPLOYEE": 2,
    "89-PASSIVEDNS": 3,
    "90-CSRF": 4,
    "91-SESSIONFIX": 3,
    "92-SAML": 3,
    "93-PWDSPRAY": 4,
    "94-COOKIEAUDIT": 3,
    "95-POSTTEST": 4,
    "96-METHODOVERRIDE": 3,
    "97-FORCEDBROWSE": 4,
    "98-CASEBYPASS": 3,
    "99-APIPAGE": 3,
    "99a-TABNAB": 2,
    "99b-APIKEYLEAK": 4,
    "99c-REDIRABUSE": 3,
    "99d-LOGTRIGGER": 2,
    "99e-XSSSTORED": 4,
    "99f-HOSTABUSE": 3,
    "99g-AUTHBYPASSADV": 4,
    "100-SSI": 3,
    "101-JSONINJECT": 3,
    "102-NULLBYTE": 2,
    "103-DOUBLEENCOD": 3,
    "104-UNICODE": 3,
    "105-POSTMSGXSS": 2,
    "106-JSONP": 2,
    "107-SRI": 2,
    "108-MIXEDCONTENT": 2,
    "109-HSTSPRELOAD": 2,
    "110-THIRDPARTYJS": 3,
    "111-BROWSERSTORAGE": 2,
    "112-RFI": 3,
    "113-WEBDAV": 3,
    "114-SNMP": 4,
    "115-BANNER": 2,
    "116-PHPINFO": 2,
    "117-SRVSTATUS": 2,
    "118-ERRORLEAK": 3,
    "119-WILDCARDDNS": 1,
    "120-DNSREBIND": 1,
    "121-IISASPNET": 3,
    "122-TOMCAT": 3,
    "123-NODEJS": 3,
    "124-LARAVEL": 3,
    "125-DJANGO": 3,
    "126-SYMFONY": 3,
    "127-CICD": 3,
    "128-DOCKER": 3,
    "129-K8S": 3,
    "130-TERRAFORM": 3,
    "131-ENVDEEP": 3,
    "132-GQLABUSE": 3,
    "133-APIVERSION": 3,
    "134-LBDETECT": 3,
    "135-VHOST": 3,
    "136-RATELIMITBYPASS": 3,
    "137-EMAILFINDER": 2,
    "138-METAGOOFIL": 2,
    "139-PORCHPIRATE": 2,
    "140-DORKHUNTER": 2,
    "141-CRTSH": 3,
    "142-GITHUBSUB": 3,
    "143-TLSX": 3,
    "144-ANALYTICSRELS": 2,
    "145-FAVIRECON": 2,
    "146-JSLUICE": 3,
    "147-SHORTSCAN": 2,
    "148-GRPCURL": 2,
    "149-LLMSEC": 4,
    "150-LLMLEAK": 3,
    "151-RAGPOISON": 3,
    "152-LLMADV": 4,
    "153-BIZLOGIC": 4,
    "154-PAYMENT": 5,
    "155-COUPON": 4,
    "156-MTENANT": 4,
    "157-2FA": 4,
    "158-SSO": 4,
    "159-SAMLADV": 4,
    "160-SSOCONF": 3,
    "161-ELECTRON": 3,
    "162-ELECTRONRCE": 4,
    "163-ELECTRONPROTO": 3,
    "164-ELECTRONUPD": 3,
    "165-DEPCONF": 4,
    "166-TYPOSQUAT": 3,
    "167-H2RAPID": 4,
    "168-H3QUIC": 3,
    "169-WEBTRANSPORT": 2,
    "170-CLIENTPP": 3,
    "171-CSSINJECT": 3,
    "172-DANGLING": 3,
    "173-SERVICEWORKER": 3,
    "174-WASMSEC": 3,
    "175-OAUTHDEVICE": 3,
    "175a-WS-DEEP": 3,
    "176-JWT2SELF": 3,
    "177-SELENIUMXSS": 3,
    "178-APIRACE": 3,
    "179-WAFBYPASS": 3,
    "180-SWAGGERABUSE": 3,
    "181-MFABYPASS": 3,
    "182-CAPTCHABYPASS": 3,
    "183-CACHEDIG": 3,
    "184-SSRFPARTIAL": 3,
    "185-MAGENTO": 3,
    "186-SHAREPOINT": 3,
    "187-CONFLUENCE": 3,
    "188-CICD": 3,
    "189-TOMCAT": 3,
    "190-BROTLIORACLE": 3,
    "191-ATO": 3,
    "192-REDOS": 3,
    "193-WEBRTC": 3,
    "194-COOKIETOSS": 3,
    "195-MIMESNIFF": 3,
    "196-PUSHAPI": 3,
}


PHASE_DEPS: Dict[str, Set[str]] = {
    # ── Root phases (no deps, self-contained) ──────────────────────────────
    "00-SCOPE": set(),
    "01-RECON": set(),
    "13-OOB": set(),
    "44-CHAIN": set(),
    "59-EMAIL-SEC": set(),
    "69-DNSZT": set(),
    "84-WHOIS": set(),
    "85-ASN": set(),
    "86-DORK": set(),
    "87-SHODAN": set(),
    "88-EMPLOYEE": set(),
    "89-PASSIVEDNS": set(),
    # ── Read all_subs.txt from 01-RECON ────────────────────────────────────
    "02-RESOLVE": {"01-RECON"},
    "03-PERMUTE": {"01-RECON"},
    # ── Read resolved.txt / hosts.txt from 02-RESOLVE ──────────────────────
    "04-SCAN": {"02-RESOLVE"},
    "14-ORIGIN": {"02-RESOLVE"},
    "18-CLOUD": {"02-RESOLVE"},
    "19-GIT": {"02-RESOLVE"},
    "20-GRAPHQL": {"02-RESOLVE"},
    "21-WAF": {"02-RESOLVE"},
    "52-SERVERLESS": {"02-RESOLVE"},
    "53-CSP": {"02-RESOLVE"},
    "60-SMTP-ENUM": {"02-RESOLVE"},
    "108-MIXEDCONTENT": {"02-RESOLVE"},
    "109-HSTSPRELOAD": {"02-RESOLVE"},
    "110-THIRDPARTYJS": {"02-RESOLVE"},
    "113-WEBDAV": {"02-RESOLVE"},
    "114-SNMP": {"02-RESOLVE"},
    # ── Read takeover / host-targets / ports from 04-SCAN ──────────────────
    "04b-TAKEOVER-VALIDATE": {"04-SCAN"},
    "05-HARVEST": {"04-SCAN"},
    "70-PORTFULL": {"04-SCAN"},
    "73-CSPBYPASS": {"04-SCAN"},
    # ── Read urls_all.txt / host_targets.txt / tech.txt from 05-HARVEST ────
    #   (most injection, auth, and check phases consume these)
    "05b-APISPEC": {"05-HARVEST"},
    "06-JSINTEL": {"05-HARVEST"},
    "07-PARAMS": {"05-HARVEST", "06-JSINTEL"},
    "08-FUZZ": {"05-HARVEST"},
    "09-VULNSCAN": {"05-HARVEST"},
    "10-TLSCMS": {"05-HARVEST"},
    "11-INJECT": {"05-HARVEST"},
    "11a-DOMXSS": {"05-HARVEST"},
    "12-SSTI": {"05-HARVEST"},
    "16a-AUTHZ": {"05-HARVEST", "08-FUZZ"},
    "16b-MASSASSIGN": {"05-HARVEST", "08-FUZZ"},
    "17-IDOR": {"05-HARVEST"},
    "22-NOSQLI": {"05-HARVEST"},
    "23-RACE": {"05-HARVEST"},
    "24-JWT": {"05-HARVEST"},
    "25-XXE": {"05-HARVEST"},
    "26-CMDINJECT": {"05-HARVEST"},
    "27-SSPP": {"05-HARVEST"},
    "28-CACHED": {"05-HARVEST"},
    "29-DEPCHECK": {"05-HARVEST"},
    "30-LFI": {"05-HARVEST"},
    "31-OPENREDIR": {"05-HARVEST"},
    "32-CLICKJACK": {"05-HARVEST"},
    "33-CRLF": {"05-HARVEST"},
    "34-RATELIMIT": {"05-HARVEST"},
    "35-CORSADV": {"05-HARVEST"},
    "37-FILEUPLOAD": {"05-HARVEST"},
    "38-SMUGGLE": {"05-HARVEST"},
    "38b-H2SMUGGLE": {"05-HARVEST"},
    "40-PWRESET": {"05-HARVEST"},
    "41-WEBSOCKET": {"05-HARVEST"},
    "42-LDAP": {"05-HARVEST"},
    "43-DESERIAL": {"05-HARVEST"},
    "46-BUCKET": {"05-HARVEST"},
    "47-CDN": {"05-HARVEST"},
    "48-CONTENT": {"05-HARVEST"},
    "49-FRAMEWORKS": {"05-HARVEST"},
    "51-HPP": {"05-HARVEST"},
    "54-WS-FUZZ": {"05-HARVEST"},
    "55-CSV-INJECT": {"05-HARVEST"},
    "56-EXPOSED-DB": {"05-HARVEST"},
    "57-DEFAULT-CREDS": {"05-HARVEST"},
    "58-HOST-INJECT": {"05-HARVEST"},
    "61-OAUTH-ADV": {"05-HARVEST"},
    "62-LOG-INJECT": {"05-HARVEST"},
    "63-DOC-ATTACK": {"05-HARVEST"},
    "64-IDEMPOTENCY": {"05-HARVEST"},
    "65-SESSION": {"05-HARVEST"},
    "66-SSRF-FULL": {"05-HARVEST"},
    "67-PATHNORM": {"05-HARVEST"},
    "68-DEPCVE": {"05-HARVEST"},
    "71-EMHARVEST": {"05-HARVEST"},
    "72-ACCOUNTENUM": {"05-HARVEST"},
    "74-GHTOOLS": {"05-HARVEST"},
    "75-MOBILEAPI": {"05-HARVEST"},
    "76-WORKFLOW": {"05-HARVEST"},
    "77-CACHEKEY": {"05-HARVEST"},
    "78-FILEUPLOADADV": {"05-HARVEST"},
    "80-STOREXSS": {"05-HARVEST"},
    "81-IDORFUZZ": {"05-HARVEST"},
    "82-OAUTHDEEP": {"05-HARVEST"},
    "83-RACEBURST": {"05-HARVEST"},
    "90-CSRF": {"05-HARVEST"},
    "91-SESSIONFIX": {"05-HARVEST"},
    "92-SAML": {"05-HARVEST"},
    "93-PWDSPRAY": {"05-HARVEST"},
    "94-COOKIEAUDIT": {"05-HARVEST"},
    "95-POSTTEST": {"05-HARVEST"},
    "96-METHODOVERRIDE": {"05-HARVEST"},
    "97-FORCEDBROWSE": {"05-HARVEST"},
    "98-CASEBYPASS": {"05-HARVEST"},
    "99-APIPAGE": {"05-HARVEST"},
    "99a-TABNAB": {"05-HARVEST"},
    "99b-APIKEYLEAK": {"05-HARVEST"},
    "99c-REDIRABUSE": {"05-HARVEST"},
    "99d-LOGTRIGGER": {"05-HARVEST"},
    "99e-XSSSTORED": {"05-HARVEST"},
    "99f-HOSTABUSE": {"05-HARVEST"},
    "99g-AUTHBYPASSADV": {"05-HARVEST"},
    "100-SSI": {"05-HARVEST"},
    "101-JSONINJECT": {"05-HARVEST"},
    "102-NULLBYTE": {"05-HARVEST"},
    "103-DOUBLEENCOD": {"05-HARVEST"},
    "104-UNICODE": {"05-HARVEST"},
    "105-POSTMSGXSS": {"05-HARVEST"},
    "106-JSONP": {"05-HARVEST"},
    "107-SRI": {"05-HARVEST"},
    "111-BROWSERSTORAGE": {"05-HARVEST"},
    "112-RFI": {"05-HARVEST"},
    "115-BANNER": {"05-HARVEST"},
    "116-PHPINFO": {"05-HARVEST"},
    "117-SRVSTATUS": {"05-HARVEST"},
    "118-ERRORLEAK": {"05-HARVEST"},
    "119-WILDCARDDNS": {"05-HARVEST"},
    "120-DNSREBIND": {"05-HARVEST"},
    "121-IISASPNET": {"05-HARVEST"},
    "122-TOMCAT": {"05-HARVEST"},
    "123-NODEJS": {"05-HARVEST"},
    "124-LARAVEL": {"05-HARVEST"},
    "125-DJANGO": {"05-HARVEST"},
    "126-SYMFONY": {"05-HARVEST"},
    "127-CICD": {"05-HARVEST"},
    "128-DOCKER": {"05-HARVEST"},
    "129-K8S": {"05-HARVEST"},
    "130-TERRAFORM": {"05-HARVEST"},
    "131-ENVDEEP": {"05-HARVEST"},
    "132-GQLABUSE": {"05-HARVEST"},
    "133-APIVERSION": {"05-HARVEST"},
    "134-LBDETECT": {"05-HARVEST"},
    "135-VHOST": {"05-HARVEST"},
    "136-RATELIMITBYPASS": {"05-HARVEST"},
    # ── Needs 07-PARAMS (enriched params from paramspider) ──────────────────
    "11b-SQLMAP": {"07-PARAMS"},
    # ── Needs 06-JSINTEL JS-analysis output ────────────────────────────────
    "15-SECRETS": {"06-JSINTEL"},
    # ── Specific cross-phase deps ──────────────────────────────────────────
    "17b-SSRFMETA": {"11-INJECT"},
    "21b-WAFBYPASS": {"21-WAF", "05-HARVEST"},
    "36-JWTADV": {"24-JWT"},
    "39-OAUTH": {"36-JWTADV"},
    "45-EVIDENCE": {"44-CHAIN"},
    "50-BUCKET-PERMS": {"18-CLOUD"},
    "79-SECRETDIFF": {"15-SECRETS"},
    "137-EMAILFINDER": {"00-SCOPE"},
    "138-METAGOOFIL": {"00-SCOPE"},
    "139-PORCHPIRATE": {"04-SCAN"},
    "140-DORKHUNTER": {"00-SCOPE"},
    "141-CRTSH": {"01-RECON"},
    "142-GITHUBSUB": {"01-RECON"},
    "143-TLSX": {"04-SCAN"},
    "144-ANALYTICSRELS": {"04-SCAN"},
    "145-FAVIRECON": {"04-SCAN"},
    "146-JSLUICE": {"06-JSINTEL"},
    "147-SHORTSCAN": {"04-SCAN"},
    "148-GRPCURL": {"04-SCAN"},
    "149-LLMSEC": {"05-HARVEST"},
    "150-LLMLEAK": {"05-HARVEST"},
    "151-RAGPOISON": {"05-HARVEST"},
    "152-LLMADV": {"05-HARVEST"},
    "153-BIZLOGIC": {"05-HARVEST"},
    "154-PAYMENT": {"05-HARVEST"},
    "155-COUPON": {"05-HARVEST"},
    "156-MTENANT": {"05-HARVEST"},
    "157-2FA": {"05-HARVEST"},
    "158-SSO": {"05-HARVEST"},
    "159-SAMLADV": {"05-HARVEST"},
    "160-SSOCONF": {"05-HARVEST"},
    "161-ELECTRON": {"05-HARVEST"},
    "162-ELECTRONRCE": {"05-HARVEST"},
    "163-ELECTRONPROTO": {"05-HARVEST"},
    "164-ELECTRONUPD": {"05-HARVEST"},
    "165-DEPCONF": {"04-SCAN"},
    "166-TYPOSQUAT": {"04-SCAN"},
    "167-H2RAPID": {"04-SCAN"},
    "168-H3QUIC": {"04-SCAN"},
    "169-WEBTRANSPORT": {"04-SCAN"},
    "170-CLIENTPP": {"05-HARVEST"},
    "171-CSSINJECT": {"05-HARVEST"},
    "172-DANGLING": {"05-HARVEST"},
    "173-SERVICEWORKER": {"04-SCAN"},
    "174-WASMSEC": {"06-JSINTEL"},
    "175-OAUTHDEVICE": {"05-HARVEST"},
    "175a-WS-DEEP": {"41-WEBSOCKET"},
    "176-JWT2SELF": {"05-HARVEST"},
    "177-SELENIUMXSS": {"05-HARVEST"},
    "178-APIRACE": {"05-HARVEST"},
    "179-WAFBYPASS": {"21-WAF"},
    "180-SWAGGERABUSE": {"05b-APISPEC"},
    "181-MFABYPASS": {"05-HARVEST"},
    "182-CAPTCHABYPASS": {"05-HARVEST"},
    "183-CACHEDIG": {"28-CACHED"},
    "184-SSRFPARTIAL": {"66-SSRF-FULL"},
    "185-MAGENTO": {"05-HARVEST"},
    "186-SHAREPOINT": {"05-HARVEST"},
    "187-CONFLUENCE": {"05-HARVEST"},
    "188-CICD": {"05-HARVEST"},
    "189-TOMCAT": {"05-HARVEST"},
    "190-BROTLIORACLE": {"05-HARVEST"},
    "191-ATO": {"05-HARVEST"},
    "192-REDOS": {"07-PARAMS"},
    "193-WEBRTC": {"05-HARVEST"},
    "194-COOKIETOSS": {"05-HARVEST"},
    "195-MIMESNIFF": {"05-HARVEST"},
    "196-PUSHAPI": {"05-HARVEST"},
}


STAGES: List[List[str]] = [
    # Stage 0 — Scope validation (must complete before any discovery)
    ["00-SCOPE"],
    # Stage 0a — Subdomain enumeration (consumes scope_validated.txt from Stage 0)
    ["01-RECON"],
    # Stage 1 — DNS resolution (needs 01-RECON output, which Stage 0 guarantees)
    ["02-RESOLVE"],
    # Stage 2 — Port scanning, WAF detection, subdomain permutation (need resolved hosts/subs)
    ["04-SCAN", "21-WAF", "03-PERMUTE"],
    # Stage 2a — DNS zone transfer (needs domain, no host dependency)
    ["69-DNSZT"],
    # Stage 2b — OSINT/recon phases (need domain only, independent of each other)
    ["84-WHOIS", "85-ASN", "86-DORK", "87-SHODAN", "88-EMPLOYEE", "89-PASSIVEDNS"],
    # Stage 3 — Harvest URLs and validate takeover candidates emitted by 04-SCAN
    ["05-HARVEST", "04b-TAKEOVER-VALIDATE"],
    # Stage 4 — URL consumers: API spec hunting and JS URL extraction need harvested URLs
    ["05b-APISPEC", "06-JSINTEL"],
    # Stage 5 — Deep JS secret/dependency prep needs urls_js.txt from 06-JSINTEL
    ["15-SECRETS"],
    # Stage 6 — Parameter discovery after JS intel/deep secret phases can enrich urls_all.txt
    ["07-PARAMS"],
    # Stage 7 — Fuzzing (throttled by WAF profile)
    ["08-FUZZ"],
    # Stage 8 — Independent parallel scans that don't need parameter corpus
    [
        "09-VULNSCAN",
        "10-TLSCMS",
        "14-ORIGIN",
        "18-CLOUD",
        "19-GIT",
        "20-GRAPHQL",
        "68-DEPCVE",
        "71-EMHARVEST",
    ],
    # Stage 9 — Main injection cluster: all consume parameter corpus, run concurrently
    [
        "11-INJECT",
        "11a-DOMXSS",
        "11b-SQLMAP",
        "12-SSTI",
        "22-NOSQLI",
        "25-XXE",
        "26-CMDINJECT",
        "27-SSPP",
        "42-LDAP",
        "43-DESERIAL",
    ],
    # Stage 10 — SSRF follow-up (triggers on confirmed SSRF from 11-INJECT)
    ["17b-SSRFMETA"],
    # Stage 11 — JWT base (dependency of 36-JWTADV)
    ["24-JWT"],
    # Stage 12 — Auth-focused cluster (JWTADV depends on 24-JWT)
    ["36-JWTADV", "72-ACCOUNTENUM"],
    # Stage 13 — Auth tests: consume JWT findings + params from earlier stages
    [
        "39-OAUTH",
        "40-PWRESET",
        "16a-AUTHZ",
        "16b-MASSASSIGN",
        "17-IDOR",
        "81-IDORFUZZ",
        "82-OAUTHDEEP",
    ],
    # Stage 13 — Long tail of independent checks (WAF-BYPASS needs 21-WAF results)
    [
        "28-CACHED",
        "29-DEPCHECK",
        "30-LFI",
        "31-OPENREDIR",
        "32-CLICKJACK",
        "33-CRLF",
        "34-RATELIMIT",
        "35-CORSADV",
        "37-FILEUPLOAD",
        "38-SMUGGLE",
        "38b-H2SMUGGLE",
        "41-WEBSOCKET",
        "21b-WAFBYPASS",
        "67-PATHNORM",
        "73-CSPBYPASS",
        "74-GHTOOLS",
        "75-MOBILEAPI",
        "76-WORKFLOW",
        "77-CACHEKEY",
        "78-FILEUPLOADADV",
        "80-STOREXSS",
    ],
    # Stage 14 — OOB callback collection + SSRF testing with OOB
    ["13-OOB", "23-RACE", "66-SSRF-FULL", "83-RACEBURST"],
    # Stage 15 — Cross-phase correlation
    ["44-CHAIN"],
    # Stage 16 — Evidence capture after correlation has written its findings
    ["45-EVIDENCE"],
    # Stage 17 — Enhancement phases: cloud/CDN/framework/idempotency
    [
        "46-BUCKET",
        "47-CDN",
        "48-CONTENT",
        "49-FRAMEWORKS",
        "64-IDEMPOTENCY",
        "65-SESSION",
        "70-PORTFULL",
    ],
    # Stage 18 — Enhancement phases v2: bucket perms + serverless + CSP + exposed DB + default creds + secret diff
    [
        "50-BUCKET-PERMS",
        "52-SERVERLESS",
        "53-CSP",
        "56-EXPOSED-DB",
        "57-DEFAULT-CREDS",
        "59-EMAIL-SEC",
        "79-SECRETDIFF",
    ],
    # Stage 19 — Injection/param-based phases: HPP, CSV, log inject need url params
    ["51-HPP", "55-CSV-INJECT", "62-LOG-INJECT", "58-HOST-INJECT"],
    # Stage 20 — WebSocket fuzzing, OAuth adv, SMTP enum, doc attack
    ["54-WS-FUZZ", "61-OAUTH-ADV", "60-SMTP-ENUM", "63-DOC-ATTACK"],
    # Stage 21 — Auth/session/access control bypass deep testing
    [
        "90-CSRF",
        "91-SESSIONFIX",
        "92-SAML",
        "93-PWDSPRAY",
        "94-COOKIEAUDIT",
        "95-POSTTEST",
        "96-METHODOVERRIDE",
        "97-FORCEDBROWSE",
        "98-CASEBYPASS",
        "99-APIPAGE",
        "99a-TABNAB",
        "99b-APIKEYLEAK",
        "99c-REDIRABUSE",
        "99d-LOGTRIGGER",
        "99e-XSSSTORED",
        "99f-HOSTABUSE",
        "99g-AUTHBYPASSADV",
    ],
    # Stage 22 — Injection, client-side, and infrastructure testing
    [
        "100-SSI",
        "101-JSONINJECT",
        "102-NULLBYTE",
        "103-DOUBLEENCOD",
        "104-UNICODE",
        "105-POSTMSGXSS",
        "106-JSONP",
        "107-SRI",
        "108-MIXEDCONTENT",
        "109-HSTSPRELOAD",
        "110-THIRDPARTYJS",
        "111-BROWSERSTORAGE",
        "112-RFI",
        "113-WEBDAV",
        "114-SNMP",
        "115-BANNER",
        "116-PHPINFO",
        "117-SRVSTATUS",
        "118-ERRORLEAK",
        "119-WILDCARDDNS",
        "120-DNSREBIND",
    ],
    # Stage 23 — CMS/framework/cloud/DevOps exposure testing
    [
        "121-IISASPNET",
        "122-TOMCAT",
        "123-NODEJS",
        "124-LARAVEL",
        "125-DJANGO",
        "126-SYMFONY",
        "127-CICD",
        "128-DOCKER",
        "129-K8S",
        "130-TERRAFORM",
        "131-ENVDEEP",
        "132-GQLABUSE",
        "133-APIVERSION",
        "134-LBDETECT",
        "135-VHOST",
        "136-RATELIMITBYPASS",
    ],
    # Stage 24 — OSINT deep: email finder, metagoofil, porch-pirate, dorks, crt.sh, github-sub
    [
        "137-EMAILFINDER",
        "138-METAGOOFIL",
        "139-PORCHPIRATE",
        "140-DORKHUNTER",
        "141-CRTSH",
        "142-GITHUBSUB",
    ],
    # Stage 25 — TLS cert intel, analytics, favicons, JS endpoints, shortlinks, gRPC
    [
        "143-TLSX",
        "144-ANALYTICSRELS",
        "145-FAVIRECON",
        "146-JSLUICE",
        "147-SHORTSCAN",
        "148-GRPCURL",
    ],
    # Stage 26 — LLM/AI security testing
    [
        "149-LLMSEC",
        "150-LLMLEAK",
        "151-RAGPOISON",
        "152-LLMADV",
    ],
    # Stage 27 — Business logic deep testing
    [
        "153-BIZLOGIC",
        "154-PAYMENT",
        "155-COUPON",
        "156-MTENANT",
        "157-2FA",
    ],
    # Stage 28 — SSO & Federation testing
    [
        "158-SSO",
        "159-SAMLADV",
        "160-SSOCONF",
    ],
    # Stage 29 — Electron/Desktop app security
    [
        "161-ELECTRON",
        "162-ELECTRONRCE",
        "163-ELECTRONPROTO",
        "164-ELECTRONUPD",
    ],
    # Stage 30 — Supply chain security
    [
        "165-DEPCONF",
        "166-TYPOSQUAT",
    ],
    # Stage 31 — Modern protocol testing
    [
        "167-H2RAPID",
        "168-H3QUIC",
        "169-WEBTRANSPORT",
    ],
    # Stage 32 — WebSocket deep fuzzing (consumes WS endpoints from phase 41)
    ["175a-WS-DEEP"],
    # Stage 32b — Client-side modern: Prototype Pollution, CSS Injection, Dangling Markup
    ["170-CLIENTPP", "171-CSSINJECT", "172-DANGLING"],
    # Stage 32c — Service Worker, WASM, JWT-to-Self XSS
    ["173-SERVICEWORKER", "174-WASMSEC", "176-JWT2SELF"],
    # Stage 32d — OAuth Device, DOM XSS dynamic, API Race, SSRF partial
    ["175-OAUTHDEVICE", "177-SELENIUMXSS", "178-APIRACE", "184-SSRFPARTIAL"],
    # Stage 32e — WAF Bypass, Swagger Abuse, MFA/CAPTCHA Bypass
    ["179-WAFBYPASS", "180-SWAGGERABUSE", "181-MFABYPASS", "182-CAPTCHABYPASS"],
    # Stage 32f — Brotli oracle
    ["190-BROTLIORACLE"],
    # Stage 33 — Cache digestion deep (consumes phase 28-CACHED findings)
    ["183-CACHEDIG"],
    # Stage 34 — CMS deep-dive: Magento, SharePoint, Confluence, CI/CD, Tomcat
    [
        "185-MAGENTO",
        "186-SHAREPOINT",
        "187-CONFLUENCE",
        "188-CICD",
        "189-TOMCAT",
    ],
    # Stage 35 — Modern web security: ATO, ReDoS, WebRTC, cookie security, PWA
    [
        "191-ATO",
        "192-REDOS",
        "193-WEBRTC",
        "194-COOKIETOSS",
        "195-MIMESNIFF",
        "196-PUSHAPI",
    ],
]


_RECON_LEVELS = {
    "1": {
        "name": "Basic reconnaissance",
        "desc": "Scope → Subs → DNS → Ports/HTTP → URLs → Report (fast, no vuln scanning)",
        "phases": {"00-SCOPE", "01-RECON", "02-RESOLVE", "04-SCAN", "05-HARVEST"},
    },
    "2": {
        "name": "Standard assessment",
        "desc": "Basic + sub perms + JS secrets + params + fuzzing + nuclei + TLS + origin IP + JWT + cache + rate-limit + WebSocket",
        "phases": {
            "00-SCOPE",
            "01-RECON",
            "02-RESOLVE",
            "03-PERMUTE",
            "04-SCAN",
            "05-HARVEST",
            "06-JSINTEL",
            "07-PARAMS",
            "08-FUZZ",
            "09-VULNSCAN",
            "10-TLSCMS",
            "14-ORIGIN",
            "24-JWT",
            "28-CACHED",
            "34-RATELIMIT",
            "41-WEBSOCKET",
        },
    },
    "full": {
        "name": "Full audit",
        "desc": "All 185 phases — recon + injection + auth/access + client-side + infrastructure + CMS + cloud + AI/LLM + business logic + SSO + supply chain + modern protocols",
        "phases": VALID_PHASES,
    },
}
